### ISSUE TITLE
Not suitable data type TemperatureMessageRepo methods

### ISSUE THREAD

**Issue by AntipovAndrey** [dmrsmglov/Temperature-Data-Server#3]
All ```Iterable<TemperatureMessage>``` from these methods are always being transformed to a List
https://github.com/dmrsmglov/Temperature-Data-Server/blob/8bd41fe2fcadf7b00c83434feb9bbbe353a033a5/src/main/java/ru/webservice/application/repositories/TemperatureMessageRepo.java#L7-L8

**Comment by dmrsmglov** [comment]
but as i know CrudRepository<? extends Object, Id>::findAllById(Iterable<Id> ids) basically returns Iterable<? extends Object>, am I right?
why i you sure that these methods will be transformed?

**Comment by AntipovAndrey** [comment]
```findAllById``` does, but it doesn't mean you have to follow the same rules while adding extra methods
