### ISSUE TITLE
TemperaturesController code cleanness

### ISSUE THREAD

**Issue by AntipovAndrey** [dmrsmglov/Temperature-Data-Server#5]
1. Default value as a hardcoded constant seems to be a bad idea since you have to check your parameter with the same hardcoded constand all over the time. Default value as an empty string may fix. 

https://github.com/dmrsmglov/Temperature-Data-Server/blob/8bd41fe2fcadf7b00c83434feb9bbbe353a033a5/src/main/java/ru/webservice/application/controllers/TemperaturesController.java#L43-L46

2. Code duplication
https://github.com/dmrsmglov/Temperature-Data-Server/blob/8bd41fe2fcadf7b00c83434feb9bbbe353a033a5/src/main/java/ru/webservice/application/controllers/TemperaturesController.java#L38-L39

https://github.com/dmrsmglov/Temperature-Data-Server/blob/8bd41fe2fcadf7b00c83434feb9bbbe353a033a5/src/main/java/ru/webservice/application/controllers/TemperaturesController.java#L61-L62

3. Unneeded split
https://github.com/dmrsmglov/Temperature-Data-Server/blob/8bd41fe2fcadf7b00c83434feb9bbbe353a033a5/src/main/java/ru/webservice/application/controllers/TemperaturesController.java#L50-L51

4. How do we know the default message of unused validator? What if ```"not validated"``` have changed?
https://github.com/dmrsmglov/Temperature-Data-Server/blob/8bd41fe2fcadf7b00c83434feb9bbbe353a033a5/src/main/java/ru/webservice/application/controllers/TemperaturesController.java#L79-L85

5. What happens when the first request carried valid coords, but invalid temps, and then the second request has invalid coords, but valid temps? Since validator's state is shared, response for the second request will contains both validation error messages
https://github.com/dmrsmglov/Temperature-Data-Server/blob/8bd41fe2fcadf7b00c83434feb9bbbe353a033a5/src/main/java/ru/webservice/application/controllers/TemperaturesController.java#L76-L88

**Comment by dmrsmglov** [comment]
In my view, I consider all your suggestions in this issue
