### ISSUE TITLE
WebSecurityConfig uses non-injected implemetation when suitable bean is available

### ISSUE THREAD

**Issue by AntipovAndrey** [dmrsmglov/Temperature-Data-Server#6]
https://github.com/dmrsmglov/Temperature-Data-Server/blob/8bd41fe2fcadf7b00c83434feb9bbbe353a033a5/src/main/java/ru/webservice/application/config/WebSecurityConfig.java#L52

**Comment by dmrsmglov** [comment]
You mean that if i wright just:
.passwordEncoder()
WebSecurityConfig will inject BCryptPasswordEncoder by itself?

**Comment by AntipovAndrey** [comment]
```.passwordEncoder ``` method accepts PasswordEncoder implementation, so you can't call it with no argument

**Comment by dmrsmglov** [comment]
So why this format is incorrect?

**Comment by AntipovAndrey** [comment]
what if you switched the PasswordEncoder implementation in your @Bean-annotated method?

**Comment by dmrsmglov** [comment]
You mean that I should declare Encoder as a property in WebSecurityConfig?
Is it good? Because I use it only in one method

**Comment by AntipovAndrey** [comment]
If you had declare it as a property of this config file, Spring would have not created an instance of this class since Encoder bean is missing yet (because method which returns this bean is not static)

**Comment by dmrsmglov** [comment]
Я запутался

**Comment by AntipovAndrey** [comment]
```java
                .dataSource(dataSource)
                .passwordEncoder(passwordEncoder())
 ```

**Comment by dmrsmglov** [comment]
Here, passwordEncoder() is method of conf class?

**Comment by AntipovAndrey** [comment]
https://github.com/dmrsmglov/Temperature-Data-Server/blob/8bd41fe2fcadf7b00c83434feb9bbbe353a033a5/src/main/java/ru/webservice/application/config/WebSecurityConfig.java#L22-L25
